apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/suricata/eve.json
        fields:
          log_type: suricata

    output.logstash:
      hosts: ["logstash:5044"]
