apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-config
data:
  suricata.yaml: |
    %YAML 1.1
    af-packet:
      - interface: eth0
        cluster-id: 99
        cluster-type: cluster_flow
        defrag: yes

    outputs:
      - eve-log:
          enabled: yes
          filetype: regular
          filename: /var/log/suricata/eve.json
          types:
            - alert
            - dns
            - http

            - tls
