apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elkstack
  template:
    metadata:
      labels:
        app: elkstack
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.0
          ports:
            - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: elkstack
spec:
  selector:
    app: elkstack
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
    - name: kibana
      port: 5601
      targetPort: 5601