apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: business-net
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eth0",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.10.0.1/24",
          "gateway": "10.10.0.1"
        }
      ],
      "routes": [],
      "dns": {}
    }
  }'
