apiVersion: apps/v1
kind: Deployment
metadata:
  name: business01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business01
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "business-net", "ips": [ "10.10.0.11/32" ] } ]'
      labels:
        app: business01
    spec:
      serviceAccountName: business-sa
      containers:
      - name: business-container
        image: cloud_project:dev
        command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business02
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "business-net", "ips": [ "10.10.0.12/32" ] } ]'
      labels:
        app: business02
    spec:
      serviceAccountName: business-sa
      containers:
      - name: business-container
        image: cloud_project:dev
        command: ["sleep", "infinity"]
