apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-suricata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-suricata
  template:
    metadata:
      labels:
        app: proxy-suricata
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
          args:
            - --provider=oidc
            - --email-domain=*
            - --upstream=http://localhost:8081  # nginx가 내부로 받음
            - --http-address=0.0.0.0:4180
            - --redirect-url=http://localhost:4180/oauth2/callback
            - --oidc-issuer-url=http://192.168.49.2:32080/realms/zt-realm
            - --client-id=proxy-client
            - --client-secret=proxysecret
            - --cookie-secret=t9PHn2l1XoZQ9ccq2KnSGQ==  # base64 랜덤값
          ports:
            - containerPort: 4180

        - name: proxy-container
          image: nginx:stable
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 8081

        - name: suricata
          image: jasonish/suricata:latest
          securityContext:
            privileged: true
          command: ["suricata", "-i", "eth0", "-c", "/etc/suricata/suricata.yaml", "-v"]
          volumeMounts:
            - name: suricata-config
              mountPath: /etc/suricata
            - name: log-volume
              mountPath: /var/log/suricata

      volumes:
        - name: nginx-config
          configMap:
            name: proxy-nginx-config
        - name: suricata-config
          configMap:
            name: suricata-configmap
        - name: log-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-suricata
spec:
  type: NodePort
  selector:
    app: proxy-suricata
  ports:
    - name: http
      port: 80
      targetPort: 4180
      nodePort: 31880
