apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suricata
  labels:
    app: suricata
spec:
  selector:
    matchLabels:
      app: suricata
  template:
    metadata:
      labels:
        app: suricata
    spec:
      hostNetwork: true
      containers:
        - name: suricata
          image: suricata-local:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
          volumeMounts:
            - name: log
              mountPath: /var/log/suricata
      volumes:
        - name: log
          hostPath:
            path: /var/log/suricata
            type: DirectoryOrCreate
