apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: business-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: business-sa
  namespace: default
roleRef:
  kind: Role
  name: business-role
  apiGroup: rbac.authorization.k8s.io
