apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: security-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: security-sa
  namespace: default
roleRef:
  kind: Role
  name: security-role
  apiGroup: rbac.authorization.k8s.io
